### PR TITLE
Fix empty map bug in aws scalardl

### PR DESCRIPTION
**Pull request by tei-k**
# Description
https://scalar-labs.atlassian.net/browse/DLT-7817

Bug in #244 

# Done
- Use `cassandra` as default value.

### CODE REVIEW

**Review by feeblefakie — APPROVED** [review]
LGTM! 

@tei-k Why terratest worked fine?

**Comment by tei-k** [comment]
> Why terratest worked fine?

@feeblefakie 

Since the current terratest is only for cassandra, So I don't use the following if statements.
```
start_on_initial_boot = var.scalardl.database == "cassandra" ? data.terraform_remote_state.cassandra.outputs.cassandra_start_on_initial_boot : false
provision_ids         = var.scalardl.database == "cassandra" ? join(",", data.terraform_remote_state.cassandra.outputs.cassandra_provision_ids) : ""
```

ref:
https://github.com/scalar-labs/scalar-terratest/blob/1bc6e1c65212ca3d8b5e94199b54c421be9f9df0/test/modules/awsdeploy/scalardl/locals.tf#L26-L27

**Comment by feeblefakie** [comment]
@ymorimo PTAL!

**Review by ymorimo — APPROVED** [review]
LGTM! Thanks! 🙏

**Pull request merged**
