### PR TITLE
Remove terratest

### PR DESCRIPTION
**Pull request by tei-k**
# Description

Migrate to [scalar-terratest](https://github.com/scalar-labs/scalar-terratest)

# Done
- Remove terratest code.
- Delete terratest workflow
- Fix CI workflow.
- Fix badge link.

# After merge
Delete unnecessary secrets. (`ARM_xxx`, `AWS_xxx`, `DOCKERHUB_xxx`)

### CODE REVIEW

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Comment by feeblefakie** [comment]
@ymorimo I'm merging it but please take a look when you get a chance.

**Review by ymorimo — COMMENTED** [review]
LGTM!

**Comment by ymorimo** [comment]
It seems like workflows are failing in #244 after this is merged. #250 should fix the problem.

**Pull request merged**
