### PR TITLE
Ignore change for vpc in private zone

### PR DESCRIPTION
**Pull request by tei-k**
# Description
https://scalar-labs.atlassian.net/browse/DLT-6828

# Done
- Fix to ignore change for vpc association in private zon

### CODE REVIEW

**Comment by feeblefakie** [comment]
@tei-k Is it still WIP ? Are you confirming something ?

**Comment by tei-k** [comment]
@feeblefakie 

>Is it still WIP ? Are you confirming something ?

I need to test it. but I don't seem to have enough permission to run it. 

https://console.aws.amazon.com/route53/v2/hostedzones#ListRecordSets/Z07983343D6DUVQRF9QUZ
- Edit
- Add vpc
- Add `vpc-0b0323ac81dd036e7`
- Save

**Comment by feeblefakie** [comment]
@tei-k I added `vpc-0b0323ac81dd036e7` but not sure if it is OK. please check.

**Comment by tei-k** [comment]
@feeblefakie 

thanks!
I checked using other vpc id, so removed `wip` prefix.

**Pull request merged**
