### PR TITLE
Specify terratest tfversion in GitHub actions

### PR DESCRIPTION
**Pull request by tei-k**
# Description
https://scalar-labs.atlassian.net/browse/DLT-7101

# Done
- Add step to install terraform in actions.
📝 Maybe better install terraform via tfenv.

# Confirm
https://github.com/scalar-labs/scalar-terraform/runs/1080429454?check_suite_focus=true

# Ref
https://medium.com/@petriautero/automate-terraform-testing-with-github-actions-and-terratest-78d74331fdf8

### CODE REVIEW

**Review by feeblefakie — DISMISSED** [review]
LGTM!

**Comment by feeblefakie** [comment]
@tei-k Still WIP?

**Comment by tei-k** [comment]
>Still WIP?

Yes, still checking... 💦

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Review by ymorimo — APPROVED** [review]
LGTM!

**Pull request merged**
