### PR TITLE
Add cluster autoscaler for eks

### PR DESCRIPTION
**Pull request by tei-k**
# Description

https://scalar-labs.atlassian.net/browse/DLT-7887
https://docs.aws.amazon.com/ja_jp/eks/latest/userguide/cluster-autoscaler.html

Add cluster autoscaler for auto scaling in `EKS`
ref: https://github.com/lablabs/terraform-aws-eks-cluster-autoscaler

# Done
- Add autoscaler to eks with `helm_release`
- Default `cluster_auto_scaling` is `false`

📝 Just only suuport `cluster_endpoint_public_access` is `public` when first deploy

### CODE REVIEW

**Review by feeblefakie — DISMISSED** [review]
LGTM!

**Review by feeblefakie — APPROVED** [review]
LGTM!

**Comment by feeblefakie** [comment]
@ymorimo PTAL!

**Review by ymorimo — APPROVED** [review]
LGTM!

**Pull request merged**
