### PR TITLE
Migrate examples

### PR DESCRIPTION
**Pull request by tei-k**
# Description

Migrate `examples` to [scalar-terraform-examples](https://github.com/scalar-labs/scalar-terraform-examples)

### CODE REVIEW

**Comment by ymorimo** [comment]
Sorry, but I added a new example in #255, so it will be needed to be migrated too after that PR is merged.

**Comment by ymorimo** [comment]
Or I might be able to update #255 to move the new example to the `scalar-terraform-examples` repo after this PR is merged.

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Review by ymorimo — APPROVED** [review]
LGTM!

**Pull request merged**
