### PR TITLE
Fix to copy schema loader image via bastion (#310)

### PR DESCRIPTION
**Pull request by tei-k**
# Description

cherry-pick #310 for `1.5` branch.

# After merge
Update `v1.5.0` or create `v1.5.1`.

### CODE REVIEW

**Comment by tei-k** [comment]
@feeblefakie 

Make new tag `v1.5.1` for 1.5 or replace `v1.5.0` ?

**Review by ymorimo — APPROVED** [review]

**Review by feeblefakie — APPROVED** [review]
LGTM! Sorry for late.

**Comment by feeblefakie** [comment]
@tei-k 
> Make new tag v1.5.1 for 1.5 or replace v1.5.0 ?
Let's create 1.5.1. 
Can we also cherry-pick other changes (bug fixes) for 1.5.1?

**Comment by tei-k** [comment]
>Can we also cherry-pick other changes (bug fixes) for 1.5.1?

Yes, What are the other changes?

**Comment by feeblefakie** [comment]
@tei-k I think there are several `bugfix` PRs after creating 1.5. I think we should add them all in 1.5.1 instead of only adding this. Thought?

**Pull request merged**
