### PR TITLE
Upgrade terraform to 0.14 for aws

### PR DESCRIPTION
**Pull request by tei-k**
# Description

https://scalar-labs.atlassian.net/browse/DLT-8330

Need to update ref of vpc after merge this [PR](https://github.com/scalar-labs/terraform-aws-vpc/pull/2)

### CODE REVIEW

**Review by feeblefakie — APPROVED** [review]
LGTM! Thank you!

**Comment by feeblefakie** [comment]
@tei-k One of the CIs is failing. Please check.

**Comment by tei-k** [comment]
> One of the CIs is failing. Please check.

same as https://github.com/scalar-labs/scalar-terraform/pull/284#issuecomment-788499912

Because of the split PR between Azure and AWS, So Azure CI failed with terraform 0.12

**Review by ymorimo — APPROVED** [review]
I manually confirmed that it worked successfully. LGTM!

**Pull request merged**
